const LOGIN_REQUEST = "LOGIN_REQUEST";
const REGISTER_REQUEST = "REGISTER_REQUEST";
const VERIFY_NUMBER = "VERIFY_NUMBER";
const LOGGED_IN = "LOGGED_IN";
const LOGGED_OUT = "LOGGED_OUT";

const CONTACTUS_REQUEST = "CONTACTUS_REQUEST";

export {
    LOGIN_REQUEST,
    REGISTER_REQUEST,
    VERIFY_NUMBER,
    LOGGED_IN,
    LOGGED_OUT,
    CONTACTUS_REQUEST,
};
